CREATE TABLE clients (
    id INT IDENTITY(1,1) PRIMARY KEY,
    [name] NVARCHAR(255) NOT NULL,
    [server] NVARCHAR(255) NOT NULL,
    [database] NVARCHAR(255) NOT NULL,
    [username] NVARCHAR(255) NULL,
    [password] NVARCHAR(255) NULL
);

INSERT INTO clients (name, [server], [database])
VALUES
    ('Acme Corp', 'wpaine.database.windows.net', 'acme_db'),
    ('Globex Inc', 'wpaine.database.windows.net', 'globex_inc'),
    ('Stark Industries', 'wpaine.database.windows.net', 'stark_ind'),
    ('Wayne Enterprises', 'wpaine.database.windows.net', 'wayne_ent'),
    ('Umbrella Corp', 'wpaine.database.windows.net', 'umbrella_db'),
    ('Oscorp', 'wpaine.database.windows.net', 'oscorp_sql'),
    ('Wonka Industries', 'wpaine.database.windows.net', 'wonka_db'),
    ('Cyberdyne Systems', 'wpaine.database.windows.net', 'cyberdyne_sql'),
    ('Weyland-Yutani', 'wpaine.database.windows.net', 'weyland_db'),
    ('Hooli', 'wpaine.database.windows.net', 'hooli_sql'),
    ('Vehement Capital Partners', 'wpaine.database.windows.net', 'vehement_db'),
    ('Massive Dynamic', 'wpaine.database.windows.net', 'massive_dyn'),
    ('Soylent Corp', 'wpaine.database.windows.net', 'soylent_db'),
    ('Rekall Inc', 'wpaine.database.windows.net', 'rekall_sql'),
    ('Virtucon', 'wpaine.database.windows.net', 'virtucon_db'),
    ('Initech', 'wpaine.database.windows.net', 'initech_sql'),
    ('Pied Piper', 'wpaine.database.windows.net', 'piedpiper_db'),
    ('Dunder Mifflin', 'wpaine.database.windows.net', 'dunder_mifflin'),
    ('Bluth Company', 'wpaine.database.windows.net', 'bluth_co'),
    ('Sterling Cooper', 'wpaine.database.windows.net', 'sterling_cooper'),
    ('Buy n Large', 'wpaine.database.windows.net', 'buynlarge_db'),
    ('Duff Brewery', 'wpaine.database.windows.net', 'duffbrewery_sql'),
    ('Prestige Worldwide', 'wpaine.database.windows.net', 'prestige_db'),
    ('Spacely Sprockets', 'wpaine.database.windows.net', 'spacely_sql'),
    ('Cogsworth Industries', 'wpaine.database.windows.net', 'cogsworth_db'),
    ('Lunar Industries', 'wpaine.database.windows.net', 'lunar_db'),
    ('Gekko & Co.', 'wpaine.database.windows.net', 'gekko_co'),
    ('Gringotts Bank', 'wpaine.database.windows.net', 'gringotts_db'),
    ('Oceanic Airlines', 'wpaine.database.windows.net', 'oceanic_air'),
    ('Omni Consumer Products', 'wpaine.database.windows.net', 'omni_cons_db'),
    ('Octan Corporation', 'wpaine.database.windows.net', 'octan_sql'),
    ('Yoyodyne Propulsion', 'wpaine.database.windows.net', 'yoyodyne_db'),
    ('Black Mesa', 'wpaine.database.windows.net', 'black_mesa'),
    ('Aperture Science', 'wpaine.database.windows.net', 'aperture_db'),
    ('Northern Lights', 'wpaine.database.windows.net', 'northern_lights'),
    ('Polybius Corp', 'wpaine.database.windows.net', 'polybius_sql'),
    ('Jurassic Park Ltd', 'wpaine.database.windows.net', 'jurassic_db'),
    ('Monarch Solutions', 'wpaine.database.windows.net', 'monarch_sql'),
    ('LexCorp', 'wpaine.database.windows.net', 'lexcorp_db'),
    ('Gotham Steel', 'wpaine.database.windows.net', 'gotham_steel'),
    ('Stagg Industries', 'wpaine.database.windows.net', 'stagg_db'),
    ('Alchemax', 'wpaine.database.windows.net', 'alchemax_sql'),
    ('Cybertronics', 'wpaine.database.windows.net', 'cybertronics_db'),
    ('Terrasave', 'wpaine.database.windows.net', 'terrasave_sql'),
    ('Vault-Tec', 'wpaine.database.windows.net', 'vault_tec'),
    ('Hyperion', 'wpaine.database.windows.net', 'hyperion_db'),
    ('Shinra Electric', 'wpaine.database.windows.net', 'shinra_db'),
    ('BiffCo', 'wpaine.database.windows.net', 'biffco_sql'),
    ('Tyrell Corporation', 'wpaine.database.windows.net', 'tyrell_db'),
    ('Globex Dynamics', 'wpaine.database.windows.net', 'globex_dynamics'),
    ('Blue Sun Corporation', 'wpaine.database.windows.net', 'bluesun_corp'),
    ('Umbrella Biohazard Countermeasure Service', 'wpaine.database.windows.net', 'umbrella_bcs'),
    ('Axiom Corporation', 'wpaine.database.windows.net', 'axiom_corp'),
    ('Red Dwarf Mining Corp', 'wpaine.database.windows.net', 'reddwarf_mining'),
    ('Future Tech Industries', 'wpaine.database.windows.net', 'futuretech_ind'),
    ('Quantum Dynamics', 'wpaine.database.windows.net', 'quantum_dynamics'),
    ('Alpha Centauri Corp', 'wpaine.database.windows.net', 'alphacentauri_corp'),
    ('Beta Systems', 'wpaine.database.windows.net', 'betasystems'),
    ('Gamma Innovations', 'wpaine.database.windows.net', 'gammainnovations'),
    ('Delta Solutions', 'wpaine.database.windows.net', 'deltasolutions'),
    ('Epsilon Enterprises', 'wpaine.database.windows.net', 'epsilonenterprises'),
    ('Zeta Technologies', 'wpaine.database.windows.net', 'zetatechnologies'),
    ('Theta Labs', 'wpaine.database.windows.net', 'thetalabs'),
    ('Lambda Holdings', 'wpaine.database.windows.net', 'lambdaholdings'),
    ('Sigma Ventures', 'wpaine.database.windows.net', 'sigmaventures'),
    ('Omega Solutions', 'wpaine.database.windows.net', 'omegasolutions'),
    ('Alpha Innovations', 'wpaine.database.windows.net', 'alphainnovations'),
    ('Beta Dynamics', 'wpaine.database.windows.net', 'betadynamics'),
    ('Gamma Partners', 'wpaine.database.windows.net', 'gammapartners'),
    ('Delta Technologies', 'wpaine.database.windows.net', 'deltatechnologies'),
    ('Epsilon Labs', 'wpaine.database.windows.net', 'epsionlabs'),
    ('Zeta Ventures', 'wpaine.database.windows.net', 'zetaventures'),
    ('Theta Holdings', 'wpaine.database.windows.net', 'thetaholdings'),
    ('Lambda Innovations', 'wpaine.database.windows.net', 'lambdainnovations'),
    ('Sigma Systems', 'wpaine.database.windows.net', 'sigmasystems'),
    ('Omega Partners', 'wpaine.database.windows.net', 'omegapartners'),
    ('Alpha Ventures', 'wpaine.database.windows.net', 'alphaventures'),
    ('Beta Holdings', 'wpaine.database.windows.net', 'betaholdings'),
    ('Gamma Solutions', 'wpaine.database.windows.net', 'gammasolutions'),
    ('Delta Innovations', 'wpaine.database.windows.net', 'deltainnovations'),
    ('Epsilon Partners', 'wpaine.database.windows.net', 'epsilonpartners'),
    ('Zeta Systems', 'wpaine.database.windows.net', 'zetasystems'),
    ('Theta Ventures', 'wpaine.database.windows.net', 'thetaventures'),
    ('Lambda Solutions', 'wpaine.database.windows.net', 'lambdasolutions'),
    ('Sigma Labs', 'wpaine.database.windows.net', 'sigmalabs'),
    ('Omega Innovations', 'wpaine.database.windows.net', 'omegainnovations'),
    ('Alpha Labs', 'wpaine.database.windows.net', 'alphalabs'),
    ('Beta Ventures', 'wpaine.database.windows.net', 'betaventures'),
    ('Gamma Holdings', 'wpaine.database.windows.net', 'gammaholdings'),
    ('Delta Partners', 'wpaine.database.windows.net', 'deltapartners'),
    ('Epsilon Solutions', 'wpaine.database.windows.net', 'epsilonsolutions'),
    ('Zeta Innovations', 'wpaine.database.windows.net', 'zetainnovations'),
    ('Theta Systems', 'wpaine.database.windows.net', 'thetasystems'),
    ('Lambda Ventures', 'wpaine.database.windows.net', 'lambdaventures'),
    ('Sigma Holdings', 'wpaine.database.windows.net', 'sigmaholdings'),
    ('Omega Labs', 'wpaine.database.windows.net', 'omegalabs'),
    ('Alpha Consulting', 'wpaine.database.windows.net', 'alphaconsulting'),
    ('Beta Consulting', 'wpaine.database.windows.net', 'betaconsulting'),
    ('Gamma Consulting', 'wpaine.database.windows.net', 'gammaconsulting'),
    ('Delta Consulting', 'wpaine.database.windows.net', 'deltaconsulting');